Refactoring scripts for command check

diff --git a/bin/opm-wine32-env b/bin/opm-wine32-env
--- a/bin/opm-wine32-env
+++ b/bin/opm-wine32-env
@@ -4,6 +4,12 @@ if ! command -v opm-version &> /dev/null; then
 PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")" || exit; pwd):$PATH"
 fi
 
+if ! command -v wine &> /dev/null; then
+    opm-println-error "Not found wine executable"
+    opm-println-error "Try: apt install wine-stable"
+    exit 1
+fi
+
 export LANG=ko_KR.utf8
 export WINEARCH=win32
 export WINEPREFIX=$OPM_HOME/var/wine32
