Refactoring opm-package script.

diff --git a/bin/opm-package b/bin/opm-package
--- a/bin/opm-package
+++ b/bin/opm-package
@@ -18,283 +18,15 @@ Available options are:
   --                Skip handling options.
 
 Available command are:
-  get-manager Install the package-manager.
-  which       Shows the full path of package-manager commands.
-  sync        Synchronize the database.
-  test        Query for package existence.
-  list        List all files owned by a given package.
-  install     Install the package.
-  remove      Remove the package.
+  get-manager   Install the package-manager.
+  which         Shows the full path of package-manager commands.
+  sync|update   Synchronize the database.
+  exist|exists|test
+                Query for package existence.
+  list          List all files owned by a given package.
+  install       Install the package.
+  erase|remove  Remove the package.
 "
-
-function exit_on_error
-{
-    local code=$?
-    if [[ $code -ne 0 ]]; then
-        return $code
-    fi
-}
-
-# ---------------
-# Linux/ArchLinux
-# ---------------
-
-function get_manager_linux_arch
-{
-    opm-println-error "Unsupported operation."
-    return 1
-}
-
-function which_linux_arch
-{
-    which pacman 2> /dev/null
-}
-
-function sync_linux_arch
-{
-    if [[ -z $(which_linux_arch) ]]; then
-        opm-println-error "Not found pacman command."
-        return 1
-    fi
-
-    sudo pacman -Sy
-}
-
-function test_linux_arch
-{
-    if [[ -z $(which_linux_arch) ]]; then
-        opm-println-error "Not found pacman command."
-        return 1
-    fi
-    if [[ $# -eq 0 ]]; then
-        opm-println-error "You must enter the package."
-        return 1
-    fi
-
-    local packages=`pacman -Q | awk '{ print $1 }'`
-    for i in $@; do
-        echo "$packages" | grep "^$i\$"
-    done
-}
-
-function list_linux_arch
-{
-    if [[ -z $(which_linux_arch) ]]; then
-        opm-println-error "Not found pacman command."
-        return 1
-    fi
-    if [[ $# -eq 0 ]]; then
-        opm-println-error "You must enter the package."
-        return 1
-    fi
-
-    pacman -Ql "$@"
-}
-
-function install_linux_arch
-{
-    if [[ -z $(which_linux_arch) ]]; then
-        opm-println-error "Not found pacman command."
-        return 1
-    fi
-    if [[ $# -eq 0 ]]; then
-        opm-println-error "You must enter the package."
-        return 1
-    fi
-
-    # [WARNING]
-    #   --noconfirm
-    #     Bypass any and all "Are you sure?" messages.
-    #     It’s not a good idea to do this unless you want to run pacman from a script.
-    sudo pacman -S "$@"
-}
-
-function remove_linux_arch
-{
-    if [[ -z $(which_linux_arch) ]]; then
-        opm-println-error "Not found pacman command."
-        return 1
-    fi
-    if [[ $# -eq 0 ]]; then
-        opm-println-error "You must enter the package."
-        return 1
-    fi
-
-    sudo pacman -Rs "$@"
-}
-
-# ------------
-# Linux/Ubuntu
-# ------------
-
-function get_manager_linux_ubuntu
-{
-    opm-println-error "Unsupported operation."
-    return 1
-}
-
-function which_linux_ubuntu
-{
-    which apt-get 2> /dev/null
-}
-
-function sync_linux_ubuntu
-{
-    if [[ -z $(which_linux_ubuntu) ]]; then
-        opm-println-error "Not found apt-get command."
-        return 1
-    fi
-
-    sudo apt-get update
-}
-
-function test_linux_ubuntu
-{
-    if [[ -z $(which_linux_ubuntu) ]]; then
-        opm-println-error "Not found apt-get command."
-        return 1
-    fi
-    if [[ $# -eq 0 ]]; then
-        opm-println-error "You must enter the package."
-        return 1
-    fi
-
-    local packages=`dpkg -l | sed -n '/+++/,$p' | sed -n '2,$p' | awk '{print $2}'`
-    for i in $@; do
-        echo "$packages" | grep "^$i\$"
-    done
-}
-
-function list_linux_ubuntu
-{
-    if [[ -z $(which_linux_ubuntu) ]]; then
-        opm-println-error "Not found apt-get command."
-        return 1
-    fi
-    if [[ $# -eq 0 ]]; then
-        opm-println-error "You must enter the package."
-        return 1
-    fi
-
-    for i in $@; do
-        dpkg -L $i | sed "s/^/$i /g"
-    done
-}
-
-function install_linux_ubuntu
-{
-    if [[ -z $(which_linux_ubuntu) ]]; then
-        opm-println-error "Not found apt-get command."
-        return 1
-    fi
-    if [[ $# -eq 0 ]]; then
-        opm-println-error "You must enter the package."
-        return 1
-    fi
-
-    sudo apt-get -y install "$@"
-}
-
-function remove_linux_ubuntu
-{
-    if [[ -z $(which_linux_ubuntu) ]]; then
-        opm-println-error "Not found apt-get command."
-        return 1
-    fi
-    if [[ $# -eq 0 ]]; then
-        opm-println-error "You must enter the package."
-        return 1
-    fi
-
-    sudo apt-get -y purge "$@"
-}
-
-# --------------
-# Darwin (macOS)
-# --------------
-
-function get_manager_darwin_brew
-{
-    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
-}
-
-function which_darwin_brew
-{
-    which brew 2> /dev/null
-}
-
-function sync_darwin_brew
-{
-    if [[ -z $(which_darwin_brew) ]]; then
-        opm-println-error "Not found brew command."
-        return 1
-    fi
-
-    brew update
-}
-
-function test_darwin_brew
-{
-    if [[ -z $(which_darwin_brew) ]]; then
-        opm-println-error "Not found brew command."
-        return 1
-    fi
-    if [[ $# -eq 0 ]]; then
-        opm-println-error "You must enter the package."
-        return 1
-    fi
-
-    local packages=`brew list -1`
-    for i in $@; do
-        echo "$packages" | grep "^$i\$"
-    done
-}
-
-function list_darwin_brew
-{
-    if [[ -z $(which_darwin_brew) ]]; then
-        opm-println-error "Not found brew command."
-        return 1
-    fi
-    if [[ $# -eq 0 ]]; then
-        opm-println-error "You must enter the package."
-        return 1
-    fi
-
-    # TODO
-}
-
-function install_darwin_brew
-{
-    if [[ -z $(which_darwin_brew) ]]; then
-        opm-println-error "Not found brew command."
-        return 1
-    fi
-    if [[ $# -eq 0 ]]; then
-        opm-println-error "You must enter the package."
-        return 1
-    fi
-
-    brew install "$@"
-}
-
-function remove_darwin_brew
-{
-    if [[ -z $(which_darwin_brew) ]]; then
-        opm-println-error "Not found brew command."
-        return 1
-    fi
-    if [[ $# -eq 0 ]]; then
-        opm-println-error "You must enter the package."
-        return 1
-    fi
-
-    brew uninstall "$@"
-}
-
-# -----------
-# Entry-point
-# -----------
 
 function find_target
 {
@@ -302,10 +34,47 @@ function find_target
     if [[ $kernel_name == darwin ]]; then
         echo "darwin_brew"
     elif [[ $kernel_name == linux ]]; then
-        echo "${kernel_name}_$(opm-distribution -i)"
+        local distribution=$(opm-distribution -i)
+        case $distribution in
+        arch)
+            echo "linux_arch_pacman"
+            ;;
+        ubuntu)
+            echo "linux_ubuntu_apt"
+            ;;
+        *)
+            opm-println-error "Unsupported distribution: $distribution"
+            return 1
+            ;;
+        esac
     else
         echo $kernel_name
     fi
+}
+
+function get_target_with_manager
+{
+    local manager=$1
+    if [[ -z $manager ]]; then
+        opm-println-error "Requires manager argument."
+        return 1
+    fi
+
+    case $manager in
+    pacman)
+        echo "linux_arch_pacman"
+        ;;
+    dpkg|apt|apt-get)
+        echo "linux_ubuntu_apt"
+        ;;
+    brew)
+        echo "darwin_brew"
+        ;;
+    *)
+        opm-println-error "Unsupported manager argument: $manager"
+        return 1
+        ;;
+    esac
 }
 
 function package_main
@@ -343,26 +112,25 @@ function package_main
 
     local target
     if [[ -n $manager ]]; then
-        case $manager in
-        pacman)
-            target=linux_arch
-            ;;
-        apt|apt-get)
-            target=linux_ubuntu
-            ;;
-        brew)
-            target=darwin_brew
-            ;;
-        *)
-            opm-println-error "Unsupported manager: $manager"
-            return 1
-            ;;
-        esac
+        target=$(get_target_with_manager $manager)
     else
         target=$(find_target)
     fi
+    local code_of_target=$?
+    if [[ $code_of_target -ne 0 ]]; then
+        return $code_of_target
+    fi
 
     VERBOSE=$verbose_flag opm-println -v -i "Selected target name: $target"
+
+    local target_source_name=opm-package-${target//_/-}
+    local which_target_source=$(which $target_source_name 2> /dev/null)
+    if [[ -z $which_target_source ]]; then
+        opm-println-error "Not found target source: $target_source_name"
+        return 1
+    fi
+
+    source "$which_target_source"
 
     if [[ $# -eq 0 ]]; then
         opm-println-error "You must enter the command."
@@ -374,20 +142,29 @@ function package_main
 
     case $command in
     get-manager)
-        get_manager_${target}
+        getmanager_${target}
         ;;
     which)
         which_${target}
         ;;
-    sync)
+    sync|update)
         sync_${target}
         ;;
-    test|list|install|remove)
+    exist|exists|test)
+        exist_${target} "$@"
+        ;;
+    list)
+        list_${target} "$@"
+        ;;
+    install)
+        install_${target} "$@"
+        ;;
+    erase|remove)
         ${command}_${target} "$@"
         ;;
     *)
         opm-println-error "Invalid command: $command"
-        return 0
+        return 1
         ;;
     esac
 }
