Fix kako path

diff --git a/bin/opm-kakao b/bin/opm-kakao
--- a/bin/opm-kakao
+++ b/bin/opm-kakao
@@ -4,4 +4,13 @@ if ! command -v opm-version &> /dev/null; then
 PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")" || exit; pwd):$PATH"
 fi
 
-opm-wine64 "$WINEPREFIX/drive_c/Program\ Files\ \(x86\)/Kakao/KakaoTalk/KakaoTalk.exe" "$@"
+WINEPREFIX=$(source opm-wine64-env && echo -n "$WINEPREFIX")
+KAKAO_SUFFIX="Program Files (x86)/Kakao/KakaoTalk/KakaoTalk.exe"
+KAKAO_PATH="$WINEPREFIX/drive_c/$KAKAO_SUFFIX"
+
+if [[ ! -f "$KAKAO_PATH" ]]; then
+    opm-println-error "Not found KakaoTalk.exe file"
+    exit 1
+fi
+
+opm-wine64 "$KAKAO_PATH" "$@" &
diff --git a/bin/opm-wine32 b/bin/opm-wine32
--- a/bin/opm-wine32
+++ b/bin/opm-wine32
@@ -4,4 +4,9 @@ if ! command -v opm-version &> /dev/null; then
 PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")" || exit; pwd):$PATH"
 fi
 
+if ! command -v wine &> /dev/null; then
+    opm-println-error "Not found wine executable"
+    exit 1
+fi
+
 source opm-wine32-env && wine "$@"
diff --git a/bin/opm-wine64cfg b/bin/opm-wine64cfg
--- a/bin/opm-wine64cfg
+++ b/bin/opm-wine64cfg
@@ -4,5 +4,10 @@ if ! command -v opm-version &> /dev/null; then
 PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")" || exit; pwd):$PATH"
 fi
 
+if ! command -v winecfg &> /dev/null; then
+    opm-println-error "Not found winecfg executable"
+    exit 1
+fi
+
 source opm-wine64-env && winecfg "$@"
 
diff --git a/bin/opm-wine64tricks b/bin/opm-wine64tricks
--- a/bin/opm-wine64tricks
+++ b/bin/opm-wine64tricks
@@ -4,4 +4,9 @@ if ! command -v opm-version &> /dev/null; then
 PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")" || exit; pwd):$PATH"
 fi
 
+if ! command -v winetricks &> /dev/null; then
+    opm-println-error "Not found winetricks executable"
+    exit 1
+fi
+
 source opm-wine64-env && winetricks "$@"
